version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:80"
      - "8081:8081"
    volumes:
      - ./server/src:/opt/arenawars/src
      - ./server/dependencies:/opt/arenawars/dependencies
      - ./server/config.ini:/opt/arenawars/config.ini
      - ./client:/usr/share/nginx/html
      - ./arenawars.sql:/opt/arenawars/arenawars.sql
