version: '3.7'
services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: arenawars
    volumes:
      - ./arenawars.sql:/docker-entrypoint-initdb.d/arenawars.sql:ro
      
  server:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./server/config.ini:/opt/arenawars/config.ini
    stdin_open: true
    tty: true

  client:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
