version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=arenawars
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./arenawars.sql:/docker-entrypoint-initdb.d/arenawars.sql
  server:
    build: ./server
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_NAME=arenawars
    ports:
      - "8081:8081"
